### ISSUE TITLE
[General] Implement the `ProgramHeader` Component (**NOT** the DefaultHeader req by OSU)

### ISSUE THREAD

**Issue by KemingHe** [devosu/research-mentorship-frontend#31]
# ToDos

- [ ] Fetch and pull current `main` branch to update your local dev env.

- [ ] `git switch --create feature-programheader-jerry` off of main and `git push -u origin feature-programheader-jerry` to start tracking.

- [ ] Implement `ProgramHeader.ts` under the `components` dir for our program specifically.
  - [ ] Use `import Link from "next/link"` instead of `<a href=...>` tags.
  - [ ] Write snpashot tests for your component, as @KemingHe for help if needed.
  - [ ] Push your tested code and create a `pull request` to main, assign @KemingHe for review.
